<?php
/**
 * Created by PhpStorm.
 * User: yunior
 * Date: 8/13/2018
 * Time: 1:39 PM
 */


use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function user_redirect_login_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        // Main module help for the redirect_user_login module.
        case 'help.page.user_redirect_login':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('redirect user after login and node after save') . '</p>';
            return $output;

        default:
    }
}


/**
 * Implements hook_form_FORM_ID_alter().
 */
function user_redirect_login_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
    // Alter login form and add own custom submit handler.
    $form['#submit'][] = '_user_redirect_login_form_submit';
}

/**
 * Custom submit handler for login form.
 */
function _user_redirect_login_form_submit($form, FormStateInterface $form_state) {
    $form_state->setRedirect('<front>');
}